# Generated by Django 4.1.7 on 2023-03-25 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('content_for_posting', models.TextField()),
                ('content_num', models.IntegerField(default=1)),
                ('input_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('content_img', models.TextField(blank=True, null=True)),
                ('reco_img', models.TextField(blank=True, null=True)),
                ('like_count', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('context', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('content_for_posting', models.TextField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.content')),
            ],
        ),
    ]
