# Generated by Django 4.1.7 on 2023-03-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='author',
        ),
        migrations.RemoveField(
            model_name='content',
            name='voter',
        ),
        migrations.AddField(
            model_name='content',
            name='reco_img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
