# Generated by Django 4.1.7 on 2023-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='like_counts',
            field=models.TextField(default=''),
        ),
    ]
