# Generated by Django 4.1.7 on 2023-03-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_content_like_counts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='like_counts',
        ),
        migrations.AddField(
            model_name='content',
            name='like_count',
            field=models.TextField(blank=True, null=True),
        ),
    ]
