# Generated by Django 4.1.7 on 2023-03-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_content_like_users_alter_content_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='like_users',
        ),
        migrations.AlterField(
            model_name='content',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
