# Generated by Django 3.2.18 on 2023-03-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_content_author_remove_content_voter_and_more'),
        ('portfolio', '0005_remove_content_like_users_alter_content_username'),
    ]

    operations = [
    ]
